version: '{branch}.{build}'

branches:
  only:
  - master

image: Visual Studio 2017

clone_folder: c:\projects\php-decimal

environment:
  PHP_SDK_BINARY_TOOLS_VER: php-sdk-2.1.1

  matrix:
    - ARCH: x86
      INT_SIZE: 32
      PHP_VER: 7.2
      VC_VER: vc15
    - ARCH: x64
      INT_SIZE: 64
      PHP_VER: 7.2
      VC_VER: vc15

install:
- cmd: cinst wget

build_script:
- cmd: >-
    "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %ARCH%

    wget https://github.com/OSTC/php-sdk-binary-tools/archive/%PHP_SDK_BINARY_TOOLS_VER%.zip --no-check-certificate -q -O php-sdk-binary-tools-%PHP_SDK_BINARY_TOOLS_VER%.zip

    7z x -y php-sdk-binary-tools-%PHP_SDK_BINARY_TOOLS_VER%.zip -oC:\projects

    move C:\projects\php-sdk-binary-tools-%PHP_SDK_BINARY_TOOLS_VER% C:\projects\php-sdk

    C:\projects\php-sdk\bin\phpsdk_setvars.bat

    git clone https://github.com/php/php-src C:\projects\php-src -b PHP-%PHP_VER% --depth=1

    mkdir C:\projects\php-src\ext\decimal

    xcopy C:\projects\php-decimal C:\projects\php-src\ext\decimal /s /e /y /q

    phpsdk_deps -u -t %VC_VER% -b %PHP_VER% -a %ARCH% -f -d C:\projects\php-src\deps

    wget http://www.bytereef.org/software/mpdecimal/releases/mpdecimal-2.4.2.zip -q

    7z x -y mpdecimal-2.4.2.zip -oC:\projects\mpdecimal

    cd C:\projects\mpdecimal\mpdecimal-2.4.2\vcbuild

    copy "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" vcvarsall.bat

    C:\projects\mpdecimal\mpdecimal-2.4.2\vcbuild\vcbuild%INT_SIZE%.bat

    mkdir C:\projects\php-decimal\bin

    copy nul C:\projects\php-src\deps\include\vcstdint.h > nul

    copy C:\projects\mpdecimal\mpdecimal-2.4.2\libmpdec\vccompat.h C:\projects\php-src\deps\include\vccompat.h

    copy C:\projects\mpdecimal\mpdecimal-2.4.2\libmpdec\vcdiv64.asm C:\projects\php-src\deps\include\vcdiv64.asm

    copy C:\projects\mpdecimal\mpdecimal-2.4.2\vcbuild\dist%INT_SIZE%\mpdecimal.h C:\projects\php-src\deps\include\mpdecimal.h

    copy C:\projects\mpdecimal\mpdecimal-2.4.2\vcbuild\dist%INT_SIZE%\libmpdec-2.4.2.lib C:\projects\php-src\deps\lib\libmpdec.lib

    copy C:\projects\mpdecimal\mpdecimal-2.4.2\vcbuild\dist%INT_SIZE%\libmpdec-2.4.2.dll C:\projects\php-decimal\bin\libmpdec.dll

    cd C:\projects\php-src

    buildconf.bat

    configure.bat --disable-all --enable-json --enable-cli --enable-zts --with-decimal=shared --with-prefix=C:\projects\php-decimal\bin --with-php-build=deps --enable-ipv6

    nmake

    nmake install

    cd C:\projects\php-decimal\bin

    echo [PHP] > php.ini

    echo extension_dir = "ext" >> php.ini

    echo extension=php_decimal.dll >> php.ini

    set TEST_PHP_EXECUTABLE=%cd%\php.exe

    php -v

    php -m

test_script:
- cmd: >-
    set REPORT_EXIT_STATUS=1

    php.exe /projects/php-src/run-tests.php /projects/php-src/ext/decimal -q --show-diff

artifacts:
  - path: bin
    name: master
    type: zip
